export const SUBTITLE_DELAY_MIN_MS = -60_000;
export const SUBTITLE_DELAY_MAX_MS = 60_000;
export const SUBTITLE_DELAY_STEP_MS = 100;
export const SUBTITLE_DELAY_OVERLAY_TIMEOUT_MS = 20_000;
export const AUTO_SYNC_REACTION_COMPENSATION_MS = 300;
export const AUTO_SYNC_VISIBLE_MARGIN_MS = 180_000;
export const AUTO_SYNC_MAX_VISIBLE_CUES = 90;